### ISSUE TITLE
.NET Core 2.2 Build Error

### ISSUE THREAD

**Issue by azampagl** [reinforced/Reinforced.Typings#102]
Unable to build .NET Core 2.2 projects. build\Reinforced.Typings.targets is throwing a generic undescriptive error. Issue is not present when I switched back to .NET Core 2.1

OS: Windows 10
SDK: Microsoft .NET Core SDK 2.2.101

    Severity   Code        Description              Project    File                                                                             Line
     Error      MSB6006     "" exited with code 1.	...         ...\.nuget\packages\reinforced.typings\1.4.95\build\Reinforced.Typings.targets    65

**Comment by philippdrebes** [comment]
Same issue here. Tried to fix it on a fork but haven't had the time to verify the change, yet.
See commit: https://github.com/philippdrebes/Reinforced.Typings/commit/2554ad278cfd96d9b14ac8e80ba6d7dd6a8edb8a

**Comment by dillenmeister** [comment]
Same here as well. The build target **ReinforcedTypingsGenerate** fails with this error: 

> No executable found matching command "dotnet-C:\Users\user\\.nuget\packages\reinforced.typings\1.4.95\tools\netcoreapp2.2\rtcli.dll"

And in the tools folder there is a netcoreapp2.1 folder but obviously not a netcoreapp2.2 folder. I think @philippdrebes approach will resolve the issue.

**Comment by dillenmeister** [comment]
Another option is to fix it here:
https://github.com/reinforced/Reinforced.Typings/blob/47aaaaa9ddb942c1fa77b8c9928157e729279ce5/Reinforced.Typings.Integrate/RtCli.cs#L124-L142

This method seems to be used to calculate the path to the tool. If the TargetFramework is "netcoreapp2.2" then "netcoreapp2.2" will be returned, but if it's for example "netcoreapp1.1" then "netcoreapp1.0" will be returned so it's a bit inconsistent.

**Comment by pavel-b-novikov** [comment]
Update will be provided after christas holidays.

**Comment by otto-gebb** [comment]
@pavel-b-novikov sorry for writing here, I didn't get a response on Twitter.
Will there be an update to the NuGet package with the latest fixes any time soon?

**Comment by pavel-b-novikov** [comment]
@otto-gebb Sorry, couldnt find you at twitter, but yeah. NuGet package update with all fixes including your PR will be published after christmas holidays (approx. 4-5 Jan)

**Comment by chriskooken** [comment]
@pavel-b-novikov  any update on this issue?

**Comment by GreenAirplane** [comment]
@pavel-b-novikov, first of all, thank you for your work! 

I would assume that the delay is related to the changes after v.1.4.95. Maybe it would be better to create v.1.4.96 just with the support of .net core 2.2? You can later release the next version with other changes. I'm sure that many users are waiting for the support of .net core 2.2 and it can be a reason why some users/companies may decide to switch to alternative solutions..

**Comment by pavel-b-novikov** [comment]
@GreenAirplane sounds reasonable. Will do

**Comment by pavel-b-novikov** [comment]
Done in 1.4.96

**Comment by philippdrebes** [comment]
@pavel-b-novikov thank you for the update.

When rebuilding my solution with 1.4.97 I always get the following build error:
> C:\Users\pd\.nuget\packages\reinforced.typings\1.4.97\build\Reinforced.Typings.targets(59,3): error MSB4062: The "Reinforced.Typings.Integrate.RtCli" task could not be loaded from the assembly C:\Users\pd\.nuget\packages\reinforced.typings\1.4.97\build\netstandard1.6\Reinforced.Typings.Integrate.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [MyProject.Web.csproj]

When I build it again, the error is gone. However, the typings are not generated either.
I did try to force the target framework but it seems to have no effect.
```xml
<RtForceTargetFramework>netcoreapp2.2</RtForceTargetFramework>
```

Is anyone experiencing the same effect?

**Comment by philippdrebes** [comment]
Just updated from MS Build Tools version 15.9.2 to 15.9.4 but unfortunately this didn't resolve the issue.

**Comment by pavel-b-novikov** [comment]
@philippdrebes Roger. Seems that problem somehow relates to [this](https://github.com/Microsoft/msbuild/issues/2111). Will fix in 1.5 release.

**Comment by chriskooken** [comment]
@pavel-b-novikov  and @philippdrebes I can confirm I'm having the same issue, although mine is complaining about System.Runtime. See Below: Thanks for the hard work @pavel-b-novikov. Should we open a new issue for this?


`The "Reinforced.Typings.Integrate.RtCli" task could not be loaded from the assembly C:\Users\chris.nuget\packages\reinforced.typings\1.4.97\build\net45\Reinforced.Typings.Integrate.dll. Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

**Comment by pavel-b-novikov** [comment]
@chriskooken Yes, please create new issue. Too much comments here already.
