### ISSUE TITLE
Fluent Configuration: Referenced console project assembly is not resolved correctly

### ISSUE THREAD

**Issue by romansp** [reinforced/Reinforced.Typings#44]
I'm using Reinforced.Typing version 1.3.1.

For the case when models are stored within Console Application, that assembly won't be resolved correctly inside `CurrentDomainOnAssemblyResolve` method.

Actually referenced console assembly will be stored inside `Bootstrapper`'s `_referencesCache`, but `LookupAssemblyPath` method will fail to find it. Because it will be looking for `{assemblyName}.dll` but not for `{assemblyName}.exe`. '.dll' extension is added to assembly name just before the call.

Line that adds `.dll `: https://github.com/reinforced/Reinforced.Typings/blob/f4a8c1263598bb3adf08e387723d367c04127ff3/Reinforced.Typings.Cli/Bootstrapper.cs#L210

Log and relevant stack-trace:
```
Reinforced.Typings CLI generator (c) 2015 by Pavel B. Novikov
Reinforced.Typings : Build warning RT0099: Unrecognized parameter: References
Looking up for assembly D:\dev\example\GraphicsTypescript\obj\Debug\GraphicsTypescript.dll
Already have full path to assembly D:\dev\example\GraphicsTypescript\obj\Debug\GraphicsTypescript.dll
Looking up for assembly Example.dll
Reinforced.Typings : Build warning RT0099: Assembly Example.dll may be resolved incorrectly
Reinforced.Typings : Unexpected error RT0999: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Reinforced.Typings.Cli.Bootstrapper.<>c__DisplayClass8_0.<ResolveFluentMethod>b__0(ConfigurationBuilder builder) in D:\dev\Reinforced.Typings\Reinforced.Typings.Cli\Bootstrapper.cs:line 105
   at Reinforced.Typings.TsExporter.Initialize() in D:\dev\Reinforced.Typings\Reinforced.Typings\TsExporter.cs:line 83
   at Reinforced.Typings.TsExporter.Export() in D:\dev\Reinforced.Typings\Reinforced.Typings\TsExporter.cs:line 180
   at Reinforced.Typings.Cli.Bootstrapper.Main(String[] args) in D:\dev\Reinforced.Typings\Reinforced.Typings.Cli\Bootstrapper.cs:line 48
```

```Example``` is an `.exe` not `.dll`.

That was somewhat mentioned in #5.

**Comment by pavel-b-novikov** [comment]
Got it. Will try to fix on weekend.

**Comment by pavel-b-novikov** [comment]
Fixed in version 1.3.2. Please check and report here if everything is ok

**Comment by romansp** [comment]
Hi Pavel, 

Just tried 1.3.5. Even though `Build warning RT0099: Assembly Example.dll may be resolved incorrectly` warning has gone, actual resolve for `.exe` assembly is still failing.

I guess it all comes up to this line. https://github.com/reinforced/Reinforced.Typings/blob/648781cc6b1b734b1ce339ee918b8e7779cb87ea/Reinforced.Typings.Cli/Bootstrapper.cs#L236

As `LookupAssemblyPath` will now handle missing extension by itself, I removed concatenation of '.dll' and got it working.

**Comment by pavel-b-novikov** [comment]
Thanks a lot for contribution! I appreciate your worktime effort. :)
