### ISSUE TITLE
Support for .NET Core 2.1

### ISSUE THREAD

**Issue by konrad147** [reinforced/Reinforced.Typings#65]
It would be great to add .NET Core 2.1 support. Currently for project with target framework `netcoreapp2.1` it throws an error: 
```
.nuget\packages\reinforced.typings\1.4.7\build\Reinforced.Typings.targets(79,3): error MSB6006: "" exited with code -2147450751
```
The same project builds fine for `netcoreapp2.0`.

**Comment by pavel-b-novikov** [comment]
New .NETs appear faster than I fix RT :(

**Comment by mqudsi** [comment]
I stumbled across this after trying to add 

```xml
<RtTargetFramework Condition="$(TargetFramework)=='netstandard2.1'">netcoreapp2.1</RtTargetFramework>
```

to my .csproj, but that didn't do the trick.

@pavel-b-novikov presuming that is the problem, it's not absolutely ideal since it may break in the future, but why don't you fall back to a generic

```xml
<RtTargetFramework>$(TargetFramework)</RtTargetFramework>
```

if none of the previous match?

**Comment by pavel-b-novikov** [comment]
Added .targets file fix in version 1.4.92
Please check it and re-open issue if it does not help

**Comment by mqudsi** [comment]
Thanks, @pavel-b-novikov

**Comment by stephtr** [comment]
Is it possible that this fix isn't working anymore with .NET Core 2.1rc1? Currently I receive `Reinforced.Typings.targets(80,3): error MSB6006: "" exited with code 1.` (Compilation works when I switching my project to 2.0)
What changes would be necessary within the .targets file?

**Comment by pavel-b-novikov** [comment]
@stephtr can you provide me with value of your ```TargetFramework``` variable within your build process?

**Comment by stephtr** [comment]
I'm using `netcoreapp2.1`.

**Comment by konrad147** [comment]
I have exactly the same problem when I set `TargetFramework` to `netcoreapp2.1`.

**Comment by Alisovsky** [comment]
Some issue here.

**Comment by pavel-b-novikov** [comment]
I promise, I will fix it this weekend. 
Sorry, too much work on other projects.

**Comment by pavel-b-novikov** [comment]
Fixed in 1.4.93

**Comment by demyte** [comment]
I am still getting this with 1.4.93:

.nuget\packages\reinforced.typings\1.4.93\build\Reinforced.Typings.targets(80,3): error MSB6006: "" exited with code 1.

**Comment by pavel-b-novikov** [comment]
Hm. Let me check

**Comment by demyte** [comment]
@pavel-b-novikov Excellent that works great!  Thanks for the super fast turnaround.

👍

**Comment by pavel-b-novikov** [comment]
@eliottrobson What is yours ```TargetFramework``` msbuild variable? (can be observed in .csproj file if you open it with notepad)

**Comment by eliottrobson** [comment]
@pavel-b-novikov `<TargetFramework>netcoreapp2.1</TargetFramework>`

**Comment by pavel-b-novikov** [comment]
@eliottrobson Please check if ```.nuget/packages/reinforced.typings/1.4.94/tools/netcoreapp2.1/rtcli.dll``` exists on your machine. 
If not, then please remove RT from your project and install it again

**Comment by Alisovsky** [comment]
I'm getting `.nuget\packages\reinforced.typings\1.4.94\build\Reinforced.Typings.targets(80,3): error MSB6006: "" exited with code -2147450730`.

I've removed `.nuget/packages/reinforced.typings` folder and reinstall the package but the issue still persists.

**Comment by pavel-b-novikov** [comment]
@eliottrobson Can you contact me via skype? nsu_the_cjay

**Comment by konrad147** [comment]
I've upgraded project to .NET Core 2.1 and locally it works fine, but when I'm trying to build it on docker container (microsoft/dotnet:2.1-sdk) then I'm getting the same error as @eliottrobson (`/root/.nuget/packages/reinforced.typings/1.4.94/build/Reinforced.Typings.targets(80,3): error MSB6006: "" exited with code 150`)

**Comment by mqudsi** [comment]
This can happen if the binary is compiled with a version of .NET Core not installed.

**Comment by demyte** [comment]
I am in the same situation as @konrad147 where locally it is all working fine, but on our build server it is failing with 

>....\.nuget\packages\reinforced.typings\1.4.94\build\Reinforced.Typings.targets(80,3): Error MSB6006: "" exited with code -2147450730.

>Process 'msbuild.exe' exited with code '1'.

This is the output of  dotnet --info

> PS>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

> Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

>Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

>.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

>.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

@mqudsi do you mean the version of dotnet core that reinforced typings was compiled under?

**Comment by konrad147** [comment]
I've discovered why it works on my local machine (thanks to @mqudsi suggestion). I have several .NET Core SDKs installed, so I tried to build docker container with each version of my local SDK. It occurred that I can build a solution with image `microsoft/dotnet:2.1.300-rc1-sdk`. So if you have same problem this may be a short workaround.

**Comment by pavel-b-novikov** [comment]
I'm sorry guys, I dont have enough experience with docker/unix so cannot help

**Comment by demyte** [comment]
@pavel-b-novikov my issue is on a windows server

What version of the SDK / Runtime are you building your DLL's with?

**Comment by pavel-b-novikov** [comment]
@demyte 
MSBuild task is for ```net45``` and ```netstandard1.6```
CLI tool is for ```net45```, ```netcoreapp1.0```, ```netcoreapp2.0```, ```netcoreapp2.1```
Library itself ```net45```, ```netcoreapp2.1```, ```netstandard1.5```, ```netstandard2.0```

**Comment by pavel-b-novikov** [comment]
I will NEVER EVER again build my frameworks for .NET previews! :/

**Comment by demyte** [comment]
@pavel-b-novikov 👍

**Comment by mqudsi** [comment]
The problem is that the nuget pulls in a match to the current project, but then that modified the csproj to eval a binary that was pulled in (identified by path) which may or may not be deployable on the host machine.

**Comment by pavel-b-novikov** [comment]
@mqudsi I'm afraid that exact binary to execute is defined not by nuget but rather by .targets file included in package.

**Comment by pavel-b-novikov** [comment]
Okay, I've published .95 version where I've moved framework detection to msbuild task instead of .targets file. Also I've added version for ```net461```. Please try this one, it might help. 

Also tricky moment: to avoid errors make sure that your mvc projects are being built for *AnyCPU* platform configuration. For some unknown reason VisualStudio sets platform to x86 by default for some MVC projects.

**Comment by tpetrina** [comment]
Hmmmm...Has anyone experienced this? 

```
/Users//.nuget/packages/reinforced.typings/1.4.95/build/Reinforced.Typings.targets(65,3): error MSB4062: The "Reinforced.Typings.Integrate.RtCli" task could not be loaded from the assembly /Users//.nuget/packages/reinforced.typings/1.4.95/build/netstandard1.6/Reinforced.Typings.Integrate.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/Users//dev/.csproj]
```

**Comment by tpetrina** [comment]
Solved, restarted my machine!

**Comment by eliottrobson** [comment]
@pavel-b-novikov 1.4.95 solves it :)

**Comment by pavel-b-novikov** [comment]
Let's try to close it while it works...
